services:
  meshobserve:
    image: github.com/fsgh42/meshobserve:${TAG:-local}
    command:
      - /usr/bin/meshobserv
      - --blocklist=""
      - --letsencrypt-cert-path=/certs
      - --domain=map.meshhessen.de
    build:
      dockerfile: Dockerfile
      target: runtime
    environment:
      MQTT_HOST: ${MQTT_HOST:-}
      MQTT_USER: ${MQTT_USER:-}
      MQTT_PASS: ${MQTT_PASS:-}
      # ACME_URL: 'https://acme-staging-v02.api.letsencrypt.org/directory'
    ports:
      - ${EXTERNAL_IP:-127.0.0.1}:80:8080
      - ${EXTERNAL_IP:-127.0.0.1}:443:8443
    restart: unless-stopped
    volumes:
      - ${PWD}/data/certs:/certs
