services:
  meshobserve:
    image: meshmap.net/meshobserve:${TAG:-local}
    command:
      ["/usr/bin/meshobserv"] #, "-b", "/blocklist.txt"]
    build:
      dockerfile: Dockerfile
      target: meshobserv
    environment:
      MQTT_HOST: ${MQTT_HOST:-""}
      MQTT_USER: ${MQTT_USER:-""}
      MQTT_PASS: ${MQTT_PASS:-""}
    ports:
      - 8080:8080
